#include <stdint.h>
#include <stdio.h>

__attribute__((weak)) uint32_t SDKLIB_OSCreateThread (void) {printf("[SystemCall] SDKLIB_OSCreateThread\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSTerminateThread (void) {printf("[SystemCall] SDKLIB_OSTerminateThread\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSSetThreadPriority (void) {printf("[SystemCall] SDKLIB_OSSetThreadPriority\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSGetThreadPriority (void) {printf("[SystemCall] SDKLIB_OSGetThreadPriority\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSSuspendThread (void) {printf("[SystemCall] SDKLIB_OSSuspendThread\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSResumeThread (void) {printf("[SystemCall] SDKLIB_OSResumeThread\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSWakeUpThread (void) {printf("[SystemCall] SDKLIB_OSWakeUpThread\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSExitThread (void) {printf("[SystemCall] SDKLIB_OSExitThread\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSSleep (void) {printf("[SystemCall] SDKLIB_OSSleep\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSCreateSemaphore (void) {printf("[SystemCall] SDKLIB_OSCreateSemaphore\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSWaitForSemaphore (void) {printf("[SystemCall] SDKLIB_OSWaitForSemaphore\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSReleaseSemaphore (void) {printf("[SystemCall] SDKLIB_OSReleaseSemaphore\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSCloseSemaphore (void) {printf("[SystemCall] SDKLIB_OSCloseSemaphore\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSCreateEvent (void) {printf("[SystemCall] SDKLIB_OSCreateEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSWaitForEvent (void) {printf("[SystemCall] SDKLIB_OSWaitForEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSSetEvent (void) {printf("[SystemCall] SDKLIB_OSSetEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSResetEvent (void) {printf("[SystemCall] SDKLIB_OSResetEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSCloseEvent (void) {printf("[SystemCall] SDKLIB_OSCloseEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSInitCriticalSection (void) {printf("[SystemCall] SDKLIB_OSInitCriticalSection\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSEnterCriticalSection (void) {printf("[SystemCall] SDKLIB_OSEnterCriticalSection\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSLeaveCriticalSection (void) {printf("[SystemCall] SDKLIB_OSLeaveCriticalSection\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSDeleteCriticalSection (void) {printf("[SystemCall] SDKLIB_OSDeleteCriticalSection\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSSetLastError (void) {printf("[SystemCall] SDKLIB_OSSetLastError\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSGetLastError (void) {printf("[SystemCall] SDKLIB_OSGetLastError\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSCreateMsgQue (void) {printf("[SystemCall] SDKLIB_OSCreateMsgQue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSPostMsgQue (void) {printf("[SystemCall] SDKLIB_OSPostMsgQue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSSendMsgQue (void) {printf("[SystemCall] SDKLIB_OSSendMsgQue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSPeekMsgQue (void) {printf("[SystemCall] SDKLIB_OSPeekMsgQue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSGetMsgQue (void) {printf("[SystemCall] SDKLIB_OSGetMsgQue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OSCloseMsgQue (void) {printf("[SystemCall] SDKLIB_OSCloseMsgQue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InterruptInitialize (void) {printf("[SystemCall] SDKLIB_InterruptInitialize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InterruptEnable (void) {printf("[SystemCall] SDKLIB_InterruptEnable\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InterruptDisable (void) {printf("[SystemCall] SDKLIB_InterruptDisable\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InterruptDone (void) {printf("[SystemCall] SDKLIB_InterruptDone\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InterruptSetMode (void) {printf("[SystemCall] SDKLIB_InterruptSetMode\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DisableAutoSync (void) {printf("[SystemCall] SDKLIB_DisableAutoSync\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_EnableAutoSync (void) {printf("[SystemCall] SDKLIB_EnableAutoSync\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_getvect (void) {printf("[SystemCall] SDKLIB_getvect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_setvect (void) {printf("[SystemCall] SDKLIB_setvect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetLCDContrast (void) {printf("[SystemCall] SDKLIB_GetLCDContrast\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetLCDContrast (void) {printf("[SystemCall] SDKLIB_SetLCDContrast\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LCDOn (void) {printf("[SystemCall] SDKLIB_LCDOn\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LCDOff (void) {printf("[SystemCall] SDKLIB_LCDOff\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CheckLCDOn (void) {printf("[SystemCall] SDKLIB_CheckLCDOn\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_Buzzer (void) {printf("[SystemCall] SDKLIB_Buzzer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_KeyBeep (void) {printf("[SystemCall] SDKLIB_KeyBeep\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetTimer1IntHandler (void) {printf("[SystemCall] SDKLIB_SetTimer1IntHandler\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetAutoPowerOff (void) {printf("[SystemCall] SDKLIB_SetAutoPowerOff\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetTimer1IntHandler (void) {printf("[SystemCall] SDKLIB_GetTimer1IntHandler\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RemapMemory (void) {printf("[SystemCall] SDKLIB_RemapMemory\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SysPowerOff (void) {printf("[SystemCall] SDKLIB_SysPowerOff\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetSysKeyState (void) {printf("[SystemCall] SDKLIB_SetSysKeyState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetSysKeyState (void) {printf("[SystemCall] SDKLIB_GetSysKeyState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetBatteryType (void) {printf("[SystemCall] SDKLIB_GetBatteryType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_BatteryLowCheck (void) {printf("[SystemCall] SDKLIB_BatteryLowCheck\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_lmalloc (void) {printf("[SystemCall] SDKLIB_lmalloc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_lcalloc (void) {printf("[SystemCall] SDKLIB_lcalloc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_lrealloc (void) {printf("[SystemCall] SDKLIB_lrealloc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__lfree (void) {printf("[SystemCall] SDKLIB__lfree\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetPenEvent (void) {printf("[SystemCall] SDKLIB_GetPenEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CheckPenEvent (void) {printf("[SystemCall] SDKLIB_CheckPenEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearPenEvent (void) {printf("[SystemCall] SDKLIB_ClearPenEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PutSystemEvent (void) {printf("[SystemCall] SDKLIB_PutSystemEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetEvent (void) {printf("[SystemCall] SDKLIB_GetEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetPendEvent (void) {printf("[SystemCall] SDKLIB_GetPendEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetEventType (void) {printf("[SystemCall] SDKLIB_SetEventType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetEventType (void) {printf("[SystemCall] SDKLIB_GetEventType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PutEvent (void) {printf("[SystemCall] SDKLIB_PutEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PutEventExt (void) {printf("[SystemCall] SDKLIB_PutEventExt\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetLastEvent (void) {printf("[SystemCall] SDKLIB_GetLastEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_TestPendEvent (void) {printf("[SystemCall] SDKLIB_TestPendEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearPendEvent (void) {printf("[SystemCall] SDKLIB_ClearPendEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearPenState (void) {printf("[SystemCall] SDKLIB_ClearPenState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearEvent (void) {printf("[SystemCall] SDKLIB_ClearEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearAllEvents (void) {printf("[SystemCall] SDKLIB_ClearAllEvents\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_TestKeyEvent (void) {printf("[SystemCall] SDKLIB_TestKeyEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetSystemVariable (void) {printf("[SystemCall] SDKLIB_SetSystemVariable\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCharWidth (void) {printf("[SystemCall] SDKLIB_GetCharWidth\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetFontHeight (void) {printf("[SystemCall] SDKLIB_GetFontHeight\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetFontType (void) {printf("[SystemCall] SDKLIB_GetFontType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetStringLength (void) {printf("[SystemCall] SDKLIB_GetStringLength\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetFontType (void) {printf("[SystemCall] SDKLIB_SetFontType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WriteAlignString (void) {printf("[SystemCall] SDKLIB_WriteAlignString\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WriteChar (void) {printf("[SystemCall] SDKLIB_WriteChar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WriteString (void) {printf("[SystemCall] SDKLIB_WriteString\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WriteStringInWindow (void) {printf("[SystemCall] SDKLIB_WriteStringInWindow\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WriteStringInWindowEx (void) {printf("[SystemCall] SDKLIB_WriteStringInWindowEx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_Printf (void) {printf("[SystemCall] SDKLIB_Printf\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PrintfXY (void) {printf("[SystemCall] SDKLIB_PrintfXY\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ShowGraphic (void) {printf("[SystemCall] SDKLIB_ShowGraphic\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SizeofGraphic (void) {printf("[SystemCall] SDKLIB_SizeofGraphic\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InitGraphic (void) {printf("[SystemCall] SDKLIB_InitGraphic\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateIcon (void) {printf("[SystemCall] SDKLIB_CreateIcon\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetCursorSize (void) {printf("[SystemCall] SDKLIB_SetCursorSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCursorSize (void) {printf("[SystemCall] SDKLIB_GetCursorSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetCursorPosition (void) {printf("[SystemCall] SDKLIB_SetCursorPosition\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCursorPosition (void) {printf("[SystemCall] SDKLIB_GetCursorPosition\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetCursorType (void) {printf("[SystemCall] SDKLIB_SetCursorType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCursorType (void) {printf("[SystemCall] SDKLIB_GetCursorType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CursorLock (void) {printf("[SystemCall] SDKLIB_CursorLock\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CursorUnlock (void) {printf("[SystemCall] SDKLIB_CursorUnlock\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetTransparentColor (void) {printf("[SystemCall] SDKLIB_SetTransparentColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetTransparentColor (void) {printf("[SystemCall] SDKLIB_GetTransparentColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_rgbSetBkColor (void) {printf("[SystemCall] SDKLIB_rgbSetBkColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_rgbSetColor (void) {printf("[SystemCall] SDKLIB_rgbSetColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_rgbGetBkColor (void) {printf("[SystemCall] SDKLIB_rgbGetBkColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_rgbGetColor (void) {printf("[SystemCall] SDKLIB_rgbGetColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetPenStyle (void) {printf("[SystemCall] SDKLIB_SetPenStyle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetPenStyle (void) {printf("[SystemCall] SDKLIB_GetPenStyle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetPenSize (void) {printf("[SystemCall] SDKLIB_GetPenSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetPenSize (void) {printf("[SystemCall] SDKLIB_SetPenSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetPixel (void) {printf("[SystemCall] SDKLIB_GetPixel\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetPixel (void) {printf("[SystemCall] SDKLIB_SetPixel\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetImage (void) {printf("[SystemCall] SDKLIB_GetImage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PutImage (void) {printf("[SystemCall] SDKLIB_PutImage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetDrawArea (void) {printf("[SystemCall] SDKLIB_SetDrawArea\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetDrawArea (void) {printf("[SystemCall] SDKLIB_GetDrawArea\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DrawLine (void) {printf("[SystemCall] SDKLIB_DrawLine\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DrawRect (void) {printf("[SystemCall] SDKLIB_DrawRect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FillRect (void) {printf("[SystemCall] SDKLIB_FillRect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DrawRoundRect (void) {printf("[SystemCall] SDKLIB_DrawRoundRect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DrawCircle (void) {printf("[SystemCall] SDKLIB_DrawCircle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FillCircle (void) {printf("[SystemCall] SDKLIB_FillCircle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DrawEllipse (void) {printf("[SystemCall] SDKLIB_DrawEllipse\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FillEllipse (void) {printf("[SystemCall] SDKLIB_FillEllipse\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InverseSetArea (void) {printf("[SystemCall] SDKLIB_InverseSetArea\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearScreen (void) {printf("[SystemCall] SDKLIB_ClearScreen\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearSetArea (void) {printf("[SystemCall] SDKLIB_ClearSetArea\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ScrollDown (void) {printf("[SystemCall] SDKLIB_ScrollDown\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ScrollLeft (void) {printf("[SystemCall] SDKLIB_ScrollLeft\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ScrollRight (void) {printf("[SystemCall] SDKLIB_ScrollRight\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ScrollUp (void) {printf("[SystemCall] SDKLIB_ScrollUp\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetRealLCD (void) {printf("[SystemCall] SDKLIB_GetRealLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetToRealLCD (void) {printf("[SystemCall] SDKLIB_SetToRealLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetToVirtualLCD (void) {printf("[SystemCall] SDKLIB_SetToVirtualLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateVirtualLCD (void) {printf("[SystemCall] SDKLIB_CreateVirtualLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DeleteVirtualLCD (void) {printf("[SystemCall] SDKLIB_DeleteVirtualLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__BitBlt (void) {printf("[SystemCall] SDKLIB__BitBlt\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___fillrect (void) {printf("[SystemCall] SDKLIB___fillrect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetActiveLCD (void) {printf("[SystemCall] SDKLIB_SetActiveLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetRealLCD (void) {printf("[SystemCall] SDKLIB_SetRealLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetActiveLCD (void) {printf("[SystemCall] SDKLIB_GetActiveLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateCompatibleLCD (void) {printf("[SystemCall] SDKLIB_CreateCompatibleLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateCompatibleImage (void) {printf("[SystemCall] SDKLIB_CreateCompatibleImage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DeleteLCD (void) {printf("[SystemCall] SDKLIB_DeleteLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SelectLCDObject (void) {printf("[SystemCall] SDKLIB_SelectLCDObject\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DeleteLCDObject (void) {printf("[SystemCall] SDKLIB_DeleteLCDObject\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetDCObject (void) {printf("[SystemCall] SDKLIB_SetDCObject\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetWindowSize (void) {printf("[SystemCall] SDKLIB_GetWindowSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetImageSize (void) {printf("[SystemCall] SDKLIB_GetImageSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetImageSizeExt (void) {printf("[SystemCall] SDKLIB_GetImageSizeExt\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ImageData (void) {printf("[SystemCall] SDKLIB_ImageData\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SizeofImage (void) {printf("[SystemCall] SDKLIB_SizeofImage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FreeImage (void) {printf("[SystemCall] SDKLIB_FreeImage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_Delay (void) {printf("[SystemCall] SDKLIB_Delay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PenDelay (void) {printf("[SystemCall] SDKLIB_PenDelay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetPenSilenceArea (void) {printf("[SystemCall] SDKLIB_GetPenSilenceArea\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetPenSilenceArea (void) {printf("[SystemCall] SDKLIB_SetPenSilenceArea\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WarningBeep (void) {printf("[SystemCall] SDKLIB_WarningBeep\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LockSystem (void) {printf("[SystemCall] SDKLIB_LockSystem\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UnlockSystem (void) {printf("[SystemCall] SDKLIB_UnlockSystem\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CopyToClipBoard (void) {printf("[SystemCall] SDKLIB_CopyToClipBoard\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CopyFromClipBoard (void) {printf("[SystemCall] SDKLIB_CopyFromClipBoard\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearClipBoard (void) {printf("[SystemCall] SDKLIB_ClearClipBoard\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetClipBoardTextLength (void) {printf("[SystemCall] SDKLIB_GetClipBoardTextLength\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetSysTime (void) {printf("[SystemCall] SDKLIB_GetSysTime\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetSysTime (void) {printf("[SystemCall] SDKLIB_SetSysTime\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PopupWaitingMsg (void) {printf("[SystemCall] SDKLIB_PopupWaitingMsg\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CloseWaitingMsg (void) {printf("[SystemCall] SDKLIB_CloseWaitingMsg\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetLanguageType (void) {printf("[SystemCall] SDKLIB_GetLanguageType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetLanguageType (void) {printf("[SystemCall] SDKLIB_SetLanguageType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetChineseFont (void) {printf("[SystemCall] SDKLIB_SetChineseFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetChineseFont (void) {printf("[SystemCall] SDKLIB_GetChineseFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetShiftState (void) {printf("[SystemCall] SDKLIB_SetShiftState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetCapsState (void) {printf("[SystemCall] SDKLIB_SetCapsState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetShiftState (void) {printf("[SystemCall] SDKLIB_GetShiftState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCapsState (void) {printf("[SystemCall] SDKLIB_GetCapsState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_Tradional2Simple (void) {printf("[SystemCall] SDKLIB_Tradional2Simple\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_Simple2Tradional (void) {printf("[SystemCall] SDKLIB_Simple2Tradional\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetEPTSLastChar (void) {printf("[SystemCall] SDKLIB_SetEPTSLastChar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PlayAllVoice (void) {printf("[SystemCall] SDKLIB_PlayAllVoice\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_StopAllVoice (void) {printf("[SystemCall] SDKLIB_StopAllVoice\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PauseAllVoice (void) {printf("[SystemCall] SDKLIB_PauseAllVoice\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ContinueAllVoice (void) {printf("[SystemCall] SDKLIB_ContinueAllVoice\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetAllVoiceState (void) {printf("[SystemCall] SDKLIB_GetAllVoiceState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RecordVoiceEx (void) {printf("[SystemCall] SDKLIB_RecordVoiceEx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PlaybackVoiceEx (void) {printf("[SystemCall] SDKLIB_PlaybackVoiceEx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetAudioHandler (void) {printf("[SystemCall] SDKLIB_SetAudioHandler\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ConvCharToUnicode (void) {printf("[SystemCall] SDKLIB_ConvCharToUnicode\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ConvStrToUnicode (void) {printf("[SystemCall] SDKLIB_ConvStrToUnicode\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CompSecretkey (void) {printf("[SystemCall] SDKLIB_CompSecretkey\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClearSecretkey (void) {printf("[SystemCall] SDKLIB_ClearSecretkey\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetUserFontHandle (void) {printf("[SystemCall] SDKLIB_SetUserFontHandle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMasterIDInfo (void) {printf("[SystemCall] SDKLIB_GetMasterIDInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ReadFollowMe (void) {printf("[SystemCall] SDKLIB_ReadFollowMe\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetPrivateState (void) {printf("[SystemCall] SDKLIB_GetPrivateState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetPrivateState (void) {printf("[SystemCall] SDKLIB_SetPrivateState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afnsplit (void) {printf("[SystemCall] SDKLIB__afnsplit\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afnmerge (void) {printf("[SystemCall] SDKLIB__afnmerge\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afcreate (void) {printf("[SystemCall] SDKLIB__afcreate\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afcreateSz (void) {printf("[SystemCall] SDKLIB__afcreateSz\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afopen (void) {printf("[SystemCall] SDKLIB__afopen\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__fclose (void) {printf("[SystemCall] SDKLIB__fclose\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__filesize (void) {printf("[SystemCall] SDKLIB__filesize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___fflush (void) {printf("[SystemCall] SDKLIB___fflush\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__fflushall (void) {printf("[SystemCall] SDKLIB__fflushall\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__rewind (void) {printf("[SystemCall] SDKLIB__rewind\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___fseek (void) {printf("[SystemCall] SDKLIB___fseek\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__ftell (void) {printf("[SystemCall] SDKLIB__ftell\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__feof (void) {printf("[SystemCall] SDKLIB__feof\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__fgetc (void) {printf("[SystemCall] SDKLIB__fgetc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__fgets (void) {printf("[SystemCall] SDKLIB__fgets\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__fread (void) {printf("[SystemCall] SDKLIB__fread\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__fputc (void) {printf("[SystemCall] SDKLIB__fputc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__fputs (void) {printf("[SystemCall] SDKLIB__fputs\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__fwrite (void) {printf("[SystemCall] SDKLIB__fwrite\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afindfirst (void) {printf("[SystemCall] SDKLIB__afindfirst\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afindnext (void) {printf("[SystemCall] SDKLIB__afindnext\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__findclose (void) {printf("[SystemCall] SDKLIB__findclose\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afgetattr (void) {printf("[SystemCall] SDKLIB__afgetattr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afsetattr (void) {printf("[SystemCall] SDKLIB__afsetattr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__aremove (void) {printf("[SystemCall] SDKLIB__aremove\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__arename (void) {printf("[SystemCall] SDKLIB__arename\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afcopy (void) {printf("[SystemCall] SDKLIB__afcopy\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__amkdir (void) {printf("[SystemCall] SDKLIB__amkdir\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__armdir (void) {printf("[SystemCall] SDKLIB__armdir\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__achdir (void) {printf("[SystemCall] SDKLIB__achdir\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__agetcurdir (void) {printf("[SystemCall] SDKLIB__agetcurdir\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__isformateddisk (void) {printf("[SystemCall] SDKLIB__isformateddisk\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__getfattype (void) {printf("[SystemCall] SDKLIB__getfattype\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__setdisk (void) {printf("[SystemCall] SDKLIB__setdisk\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__getdisk (void) {printf("[SystemCall] SDKLIB__getdisk\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__getdiskchar (void) {printf("[SystemCall] SDKLIB__getdiskchar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__setdiskchar (void) {printf("[SystemCall] SDKLIB__setdiskchar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__getdisknum (void) {printf("[SystemCall] SDKLIB__getdisknum\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FSGetDiskRoomState (void) {printf("[SystemCall] SDKLIB_FSGetDiskRoomState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__OpenFile (void) {printf("[SystemCall] SDKLIB__OpenFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__OpenFileEx (void) {printf("[SystemCall] SDKLIB__OpenFileEx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__OpenFileW (void) {printf("[SystemCall] SDKLIB__OpenFileW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__CloseFile (void) {printf("[SystemCall] SDKLIB__CloseFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__ReadFile (void) {printf("[SystemCall] SDKLIB__ReadFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__FseekFile (void) {printf("[SystemCall] SDKLIB__FseekFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__FileSize (void) {printf("[SystemCall] SDKLIB__FileSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__OpenSubFile (void) {printf("[SystemCall] SDKLIB__OpenSubFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__TellFile (void) {printf("[SystemCall] SDKLIB__TellFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBSave (void) {printf("[SystemCall] SDKLIB_DBSave\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBSaveAll (void) {printf("[SystemCall] SDKLIB_DBSaveAll\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBOpenUserFile (void) {printf("[SystemCall] SDKLIB_DBOpenUserFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBCreate (void) {printf("[SystemCall] SDKLIB_DBCreate\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBCreateSZ (void) {printf("[SystemCall] SDKLIB_DBCreateSZ\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBOpen (void) {printf("[SystemCall] SDKLIB_DBOpen\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBClose (void) {printf("[SystemCall] SDKLIB_DBClose\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBRemove (void) {printf("[SystemCall] SDKLIB_DBRemove\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBEmpty (void) {printf("[SystemCall] SDKLIB_DBEmpty\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBOptimize (void) {printf("[SystemCall] SDKLIB_DBOptimize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBRepair (void) {printf("[SystemCall] SDKLIB_DBRepair\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBGetNewRecordPID (void) {printf("[SystemCall] SDKLIB_DBGetNewRecordPID\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBGetNewRecordID (void) {printf("[SystemCall] SDKLIB_DBGetNewRecordID\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBCreateNewRecord (void) {printf("[SystemCall] SDKLIB_DBCreateNewRecord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBInsertRecord (void) {printf("[SystemCall] SDKLIB_DBInsertRecord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBModifyRecord (void) {printf("[SystemCall] SDKLIB_DBModifyRecord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBRemoveRecord (void) {printf("[SystemCall] SDKLIB_DBRemoveRecord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBReadRecord (void) {printf("[SystemCall] SDKLIB_DBReadRecord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBGetRecordTime (void) {printf("[SystemCall] SDKLIB_DBGetRecordTime\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBGetRecordDate (void) {printf("[SystemCall] SDKLIB_DBGetRecordDate\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBGetRecordPid (void) {printf("[SystemCall] SDKLIB_DBGetRecordPid\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBGetCurRecordCount (void) {printf("[SystemCall] SDKLIB_DBGetCurRecordCount\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBOverLoadSortFunc (void) {printf("[SystemCall] SDKLIB_DBOverLoadSortFunc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBGetRecPidState (void) {printf("[SystemCall] SDKLIB_DBGetRecPidState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DBGetDBState (void) {printf("[SystemCall] SDKLIB_DBGetDBState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetSystemDirectory (void) {printf("[SystemCall] SDKLIB__GetSystemDirectory\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetTempPath (void) {printf("[SystemCall] SDKLIB__GetTempPath\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetPrivateProfileInt (void) {printf("[SystemCall] SDKLIB__GetPrivateProfileInt\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetPrivateProfileString (void) {printf("[SystemCall] SDKLIB__GetPrivateProfileString\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__WritePrivateProfileString (void) {printf("[SystemCall] SDKLIB__WritePrivateProfileString\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetTadCityNo (void) {printf("[SystemCall] SDKLIB_GetTadCityNo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RunApplicationA (void) {printf("[SystemCall] SDKLIB_RunApplicationA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetApplicationNameA (void) {printf("[SystemCall] SDKLIB_GetApplicationNameA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadProgramA (void) {printf("[SystemCall] SDKLIB_LoadProgramA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FreeProgram (void) {printf("[SystemCall] SDKLIB_FreeProgram\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ExecuteProgram (void) {printf("[SystemCall] SDKLIB_ExecuteProgram\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCurrentPathA (void) {printf("[SystemCall] SDKLIB_GetCurrentPathA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ProgramIsRunningA (void) {printf("[SystemCall] SDKLIB_ProgramIsRunningA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FindApplications (void) {printf("[SystemCall] SDKLIB_FindApplications\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FreeFindApplications (void) {printf("[SystemCall] SDKLIB_FreeFindApplications\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetApplicationInfo (void) {printf("[SystemCall] SDKLIB_GetApplicationInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateAppView (void) {printf("[SystemCall] SDKLIB_CreateAppView\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_TextPicker (void) {printf("[SystemCall] SDKLIB_TextPicker\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMonDays (void) {printf("[SystemCall] SDKLIB_GetMonDays\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetWeekDay (void) {printf("[SystemCall] SDKLIB_GetWeekDay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ConvSolarToLunar (void) {printf("[SystemCall] SDKLIB_ConvSolarToLunar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ConvLunarToSolar (void) {printf("[SystemCall] SDKLIB_ConvLunarToSolar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetLeapMonth (void) {printf("[SystemCall] SDKLIB_GetLeapMonth\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateEdit (void) {printf("[SystemCall] SDKLIB_CreateEdit\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_EDInitEdit (void) {printf("[SystemCall] SDKLIB_EDInitEdit\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_EDDraw (void) {printf("[SystemCall] SDKLIB_EDDraw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_EDDrawText (void) {printf("[SystemCall] SDKLIB_EDDrawText\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_EDHandleEvent (void) {printf("[SystemCall] SDKLIB_EDHandleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertTextField (void) {printf("[SystemCall] SDKLIB_InsertTextField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ReplaceEditBuffer (void) {printf("[SystemCall] SDKLIB_ReplaceEditBuffer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetEditCmdFunc (void) {printf("[SystemCall] SDKLIB_SetEditCmdFunc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetEditCmdFunc (void) {printf("[SystemCall] SDKLIB_GetEditCmdFunc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetEditFunctionMenuState (void) {printf("[SystemCall] SDKLIB_SetEditFunctionMenuState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DatePicker (void) {printf("[SystemCall] SDKLIB_DatePicker\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateBoolDateField (void) {printf("[SystemCall] SDKLIB_CreateBoolDateField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateBoolMenuField (void) {printf("[SystemCall] SDKLIB_CreateBoolMenuField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateBoolField (void) {printf("[SystemCall] SDKLIB_CreateBoolField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateBoolTextField (void) {printf("[SystemCall] SDKLIB_CreateBoolTextField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateTimeField (void) {printf("[SystemCall] SDKLIB_CreateTimeField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateDateField (void) {printf("[SystemCall] SDKLIB_CreateDateField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateDoubleTimeField (void) {printf("[SystemCall] SDKLIB_CreateDoubleTimeField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateNumericField (void) {printf("[SystemCall] SDKLIB_CreateNumericField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PDATEFIELD_draw (void) {printf("[SystemCall] SDKLIB_PDATEFIELD_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PDATEFIELD_handleEvent (void) {printf("[SystemCall] SDKLIB_PDATEFIELD_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PDATEFIELD_setState (void) {printf("[SystemCall] SDKLIB_PDATEFIELD_setState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PNUMERICFIELD_handleEvent (void) {printf("[SystemCall] SDKLIB_PNUMERICFIELD_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PBOOLFIELD_draw (void) {printf("[SystemCall] SDKLIB_PBOOLFIELD_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_MessageBox (void) {printf("[SystemCall] SDKLIB_MessageBox\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateMessageBox (void) {printf("[SystemCall] SDKLIB_CreateMessageBox\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_NumericPicker (void) {printf("[SystemCall] SDKLIB_NumericPicker\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetNumPkValidHandle (void) {printf("[SystemCall] SDKLIB_SetNumPkValidHandle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateDetailView (void) {printf("[SystemCall] SDKLIB_CreateDetailView\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PDETAILVIEW_draw (void) {printf("[SystemCall] SDKLIB_PDETAILVIEW_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_NumericToStr (void) {printf("[SystemCall] SDKLIB_NumericToStr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_StrToNumeric (void) {printf("[SystemCall] SDKLIB_StrToNumeric\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_AllocBlock (void) {printf("[SystemCall] SDKLIB_AllocBlock\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FreeBlock (void) {printf("[SystemCall] SDKLIB_FreeBlock\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RelatedKeyButton (void) {printf("[SystemCall] SDKLIB_RelatedKeyButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RelatedKeyButtonEx (void) {printf("[SystemCall] SDKLIB_RelatedKeyButtonEx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UnRelatedKeyButton (void) {printf("[SystemCall] SDKLIB_UnRelatedKeyButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateButton (void) {printf("[SystemCall] SDKLIB_CreateButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeButton (void) {printf("[SystemCall] SDKLIB_ChangeButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertButton (void) {printf("[SystemCall] SDKLIB_InsertButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateStatic (void) {printf("[SystemCall] SDKLIB_CreateStatic\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PBUTTON_draw (void) {printf("[SystemCall] SDKLIB_PBUTTON_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertImageClip (void) {printf("[SystemCall] SDKLIB_InsertImageClip\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreatePageArrow (void) {printf("[SystemCall] SDKLIB_CreatePageArrow\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertPgUpDn (void) {printf("[SystemCall] SDKLIB_InsertPgUpDn\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateHorPageArrow (void) {printf("[SystemCall] SDKLIB_CreateHorPageArrow\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateControlMenu (void) {printf("[SystemCall] SDKLIB_CreateControlMenu\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateMenuField (void) {printf("[SystemCall] SDKLIB_CreateMenuField\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateNumberSet (void) {printf("[SystemCall] SDKLIB_CreateNumberSet\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateStackedList (void) {printf("[SystemCall] SDKLIB_CreateStackedList\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateSlider (void) {printf("[SystemCall] SDKLIB_CreateSlider\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateProgress (void) {printf("[SystemCall] SDKLIB_CreateProgress\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateRadioButton (void) {printf("[SystemCall] SDKLIB_CreateRadioButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PPROGRESSetPos (void) {printf("[SystemCall] SDKLIB_PPROGRESSetPos\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PPROGRESSetRange (void) {printf("[SystemCall] SDKLIB_PPROGRESSetRange\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSLIDER_SetPos (void) {printf("[SystemCall] SDKLIB_PSLIDER_SetPos\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSLIDER_SetRange (void) {printf("[SystemCall] SDKLIB_PSLIDER_SetRange\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSLIDER_handleEvent (void) {printf("[SystemCall] SDKLIB_PSLIDER_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IsRadioButtonCheck (void) {printf("[SystemCall] SDKLIB_IsRadioButtonCheck\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CheckDeskRadioButton (void) {printf("[SystemCall] SDKLIB_CheckDeskRadioButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PNUMBERSET_handleEvent (void) {printf("[SystemCall] SDKLIB_PNUMBERSET_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PMENUFIELD_draw (void) {printf("[SystemCall] SDKLIB_PMENUFIELD_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PMENUFIELD_handleEvent (void) {printf("[SystemCall] SDKLIB_PMENUFIELD_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PCONTROLMENU_draw (void) {printf("[SystemCall] SDKLIB_PCONTROLMENU_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PCONTROLMENU_handleEvent (void) {printf("[SystemCall] SDKLIB_PCONTROLMENU_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PVIEW_draw (void) {printf("[SystemCall] SDKLIB_PVIEW_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PVIEW_EraseBackGround (void) {printf("[SystemCall] SDKLIB_PVIEW_EraseBackGround\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PVIEW_handleEvent (void) {printf("[SystemCall] SDKLIB_PVIEW_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PVIEW_setState (void) {printf("[SystemCall] SDKLIB_PVIEW_setState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PGROUP_draw (void) {printf("[SystemCall] SDKLIB_PGROUP_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PGROUP_handleEvent (void) {printf("[SystemCall] SDKLIB_PGROUP_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PGROUP_insert (void) {printf("[SystemCall] SDKLIB_PGROUP_insert\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PGROUP_redraw (void) {printf("[SystemCall] SDKLIB_PGROUP_redraw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PGROUP_setCurrent (void) {printf("[SystemCall] SDKLIB_PGROUP_setCurrent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PGROUP_setState (void) {printf("[SystemCall] SDKLIB_PGROUP_setState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PGROUP_execute (void) {printf("[SystemCall] SDKLIB_PGROUP_execute\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PGROUP_preView (void) {printf("[SystemCall] SDKLIB_PGROUP_preView\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateDeskBox (void) {printf("[SystemCall] SDKLIB_CreateDeskBox\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PDESKBOX_draw (void) {printf("[SystemCall] SDKLIB_PDESKBOX_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PDESKBOX_drawTitle (void) {printf("[SystemCall] SDKLIB_PDESKBOX_drawTitle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PDESKBOX_handleEvent (void) {printf("[SystemCall] SDKLIB_PDESKBOX_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PDESKBOX_redraw (void) {printf("[SystemCall] SDKLIB_PDESKBOX_redraw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_Destroy (void) {printf("[SystemCall] SDKLIB_Destroy\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DeskBox_construct (void) {printf("[SystemCall] SDKLIB_DeskBox_construct\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DrawDeskBoxBound (void) {printf("[SystemCall] SDKLIB_DrawDeskBoxBound\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeCommandMenu (void) {printf("[SystemCall] SDKLIB_ChangeCommandMenu\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetDeskBoxReturn (void) {printf("[SystemCall] SDKLIB_SetDeskBoxReturn\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ExecView (void) {printf("[SystemCall] SDKLIB_ExecView\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetExitWordVal (void) {printf("[SystemCall] SDKLIB_SetExitWordVal\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetExitWordVal (void) {printf("[SystemCall] SDKLIB_GetExitWordVal\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetCurModeWord (void) {printf("[SystemCall] SDKLIB_SetCurModeWord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCurModeWord (void) {printf("[SystemCall] SDKLIB_GetCurModeWord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertTitleBarButton (void) {printf("[SystemCall] SDKLIB_InsertTitleBarButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_Delete (void) {printf("[SystemCall] SDKLIB_Delete\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DisableCommand (void) {printf("[SystemCall] SDKLIB_DisableCommand\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_EnableCommand (void) {printf("[SystemCall] SDKLIB_EnableCommand\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InverseSetAreaArc (void) {printf("[SystemCall] SDKLIB_InverseSetAreaArc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InverseSetAreaColor (void) {printf("[SystemCall] SDKLIB_InverseSetAreaColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InverseSetAreaArcColor (void) {printf("[SystemCall] SDKLIB_InverseSetAreaArcColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SendMessage (void) {printf("[SystemCall] SDKLIB_SendMessage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SendMessageExt (void) {printf("[SystemCall] SDKLIB_SendMessageExt\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetPreView (void) {printf("[SystemCall] SDKLIB_GetPreView\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetFocuseItem (void) {printf("[SystemCall] SDKLIB_SetFocuseItem\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetTabOrder (void) {printf("[SystemCall] SDKLIB_SetTabOrder\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetDeskEntry (void) {printf("[SystemCall] SDKLIB_GetDeskEntry\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetDeskItem (void) {printf("[SystemCall] SDKLIB_GetDeskItem\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_QueryByCommand (void) {printf("[SystemCall] SDKLIB_QueryByCommand\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMaxScrX (void) {printf("[SystemCall] SDKLIB_GetMaxScrX\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMaxScrY (void) {printf("[SystemCall] SDKLIB_GetMaxScrY\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetDeskClientRect (void) {printf("[SystemCall] SDKLIB_GetDeskClientRect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InvalidateRect (void) {printf("[SystemCall] SDKLIB_InvalidateRect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertSplitViewFrame (void) {printf("[SystemCall] SDKLIB_InsertSplitViewFrame\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateSplitView (void) {printf("[SystemCall] SDKLIB_CreateSplitView\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertSplitView (void) {printf("[SystemCall] SDKLIB_InsertSplitView\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSPLITVIEW_draw (void) {printf("[SystemCall] SDKLIB_PSPLITVIEW_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSPLITVIEW_handleEvent (void) {printf("[SystemCall] SDKLIB_PSPLITVIEW_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSPLITVIEW_setState (void) {printf("[SystemCall] SDKLIB_PSPLITVIEW_setState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertMultiPage (void) {printf("[SystemCall] SDKLIB_InsertMultiPage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PPAGE_draw (void) {printf("[SystemCall] SDKLIB_PPAGE_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PPAGE_handleEvent (void) {printf("[SystemCall] SDKLIB_PPAGE_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PMPAGE_insertPage (void) {printf("[SystemCall] SDKLIB_PMPAGE_insertPage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PMPAGE_handleEvent (void) {printf("[SystemCall] SDKLIB_PMPAGE_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ConverNumToStr (void) {printf("[SystemCall] SDKLIB_ConverNumToStr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ConverTimeToStr (void) {printf("[SystemCall] SDKLIB_ConverTimeToStr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DateToString (void) {printf("[SystemCall] SDKLIB_DateToString\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_TimeToString (void) {printf("[SystemCall] SDKLIB_TimeToString\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ZfxGetWeekDay (void) {printf("[SystemCall] SDKLIB_ZfxGetWeekDay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WriteNumber (void) {printf("[SystemCall] SDKLIB_WriteNumber\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ConverDateToStr (void) {printf("[SystemCall] SDKLIB_ConverDateToStr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PopUpList (void) {printf("[SystemCall] SDKLIB_PopUpList\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PressAtRange (void) {printf("[SystemCall] SDKLIB_PressAtRange\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PressAtButton (void) {printf("[SystemCall] SDKLIB_PressAtButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PressAtButtonInv (void) {printf("[SystemCall] SDKLIB_PressAtButtonInv\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PressAtButtonIconAddr (void) {printf("[SystemCall] SDKLIB_PressAtButtonIconAddr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PressAtButtonIcon (void) {printf("[SystemCall] SDKLIB_PressAtButtonIcon\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IsSystemItemID (void) {printf("[SystemCall] SDKLIB_IsSystemItemID\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WaitingMessageBox (void) {printf("[SystemCall] SDKLIB_WaitingMessageBox\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateCalendar (void) {printf("[SystemCall] SDKLIB_CreateCalendar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PCALENDAR_draw (void) {printf("[SystemCall] SDKLIB_PCALENDAR_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PCALENDAR_handleEvent (void) {printf("[SystemCall] SDKLIB_PCALENDAR_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateScrollBar (void) {printf("[SystemCall] SDKLIB_CreateScrollBar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertScrollBar (void) {printf("[SystemCall] SDKLIB_InsertScrollBar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertScrollBarPosition (void) {printf("[SystemCall] SDKLIB_InsertScrollBarPosition\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSCROLLBAR_draw (void) {printf("[SystemCall] SDKLIB_PSCROLLBAR_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSCROLLBAR_redraw (void) {printf("[SystemCall] SDKLIB_PSCROLLBAR_redraw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PSCROLLBAR_handleEvent (void) {printf("[SystemCall] SDKLIB_PSCROLLBAR_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeScrollBarValue (void) {printf("[SystemCall] SDKLIB_ChangeScrollBarValue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeScrollBarStep (void) {printf("[SystemCall] SDKLIB_ChangeScrollBarStep\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetScrollBarValue (void) {printf("[SystemCall] SDKLIB_SetScrollBarValue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetScrollBarStep (void) {printf("[SystemCall] SDKLIB_SetScrollBarStep\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateLister (void) {printf("[SystemCall] SDKLIB_CreateLister\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLISTER_draw (void) {printf("[SystemCall] SDKLIB_PLISTER_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLISTER_handleEvent (void) {printf("[SystemCall] SDKLIB_PLISTER_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLISTER_writeItem (void) {printf("[SystemCall] SDKLIB_PLISTER_writeItem\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLISTER_penDownAct (void) {printf("[SystemCall] SDKLIB_PLISTER_penDownAct\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLISTER_changeFocuseAct (void) {printf("[SystemCall] SDKLIB_PLISTER_changeFocuseAct\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeListRowHeight (void) {printf("[SystemCall] SDKLIB_ChangeListRowHeight\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeListItemSum (void) {printf("[SystemCall] SDKLIB_ChangeListItemSum\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateLongLister (void) {printf("[SystemCall] SDKLIB_CreateLongLister\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLONGLISTER_draw (void) {printf("[SystemCall] SDKLIB_PLONGLISTER_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLONGLISTER_handleEvent (void) {printf("[SystemCall] SDKLIB_PLONGLISTER_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLONGLISTER_changeFocuseAct (void) {printf("[SystemCall] SDKLIB_PLONGLISTER_changeFocuseAct\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLONGLISTER_writeItem (void) {printf("[SystemCall] SDKLIB_PLONGLISTER_writeItem\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PLONGLISTER_penDownAct (void) {printf("[SystemCall] SDKLIB_PLONGLISTER_penDownAct\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeLongListItemSum (void) {printf("[SystemCall] SDKLIB_ChangeLongListItemSum\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeLongListRowHeight (void) {printf("[SystemCall] SDKLIB_ChangeLongListRowHeight\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetSysColorConfig (void) {printf("[SystemCall] SDKLIB_SetSysColorConfig\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetSysColorConfig (void) {printf("[SystemCall] SDKLIB_GetSysColorConfig\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetSysColor (void) {printf("[SystemCall] SDKLIB_GetSysColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetSysColor (void) {printf("[SystemCall] SDKLIB_SetSysColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetDefaultSysIconCfg (void) {printf("[SystemCall] SDKLIB_SetDefaultSysIconCfg\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DrawGradientRect (void) {printf("[SystemCall] SDKLIB_DrawGradientRect\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_TimePicker (void) {printf("[SystemCall] SDKLIB_TimePicker\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetOpenFileName (void) {printf("[SystemCall] SDKLIB__GetOpenFileName\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetSaveFileName (void) {printf("[SystemCall] SDKLIB__GetSaveFileName\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetNextFileName (void) {printf("[SystemCall] SDKLIB__GetNextFileName\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertFileFilter (void) {printf("[SystemCall] SDKLIB_InsertFileFilter\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PFILEFILTER_draw (void) {printf("[SystemCall] SDKLIB_PFILEFILTER_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PFILEFILTER_handleEvent (void) {printf("[SystemCall] SDKLIB_PFILEFILTER_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PFILEFILTER_chgColumnText (void) {printf("[SystemCall] SDKLIB_PFILEFILTER_chgColumnText\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PFILEFILTER_setPathInfo (void) {printf("[SystemCall] SDKLIB_PFILEFILTER_setPathInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PFILEFILTER_getFillMode (void) {printf("[SystemCall] SDKLIB_PFILEFILTER_getFillMode\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PFILEFILTER_setFillMode (void) {printf("[SystemCall] SDKLIB_PFILEFILTER_setFillMode\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PFILEFILTER_getItemName (void) {printf("[SystemCall] SDKLIB_PFILEFILTER_getItemName\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PFILEFILTER_writeColumn0 (void) {printf("[SystemCall] SDKLIB_PFILEFILTER_writeColumn0\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetFileExecuteFunction (void) {printf("[SystemCall] SDKLIB_GetFileExecuteFunction\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__EditFileName (void) {printf("[SystemCall] SDKLIB__EditFileName\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_GetHandActiveState (void) {printf("[SystemCall] SDKLIB_IME_GetHandActiveState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_GetCtrlSize (void) {printf("[SystemCall] SDKLIB_IME_GetCtrlSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_ActiveCtrl (void) {printf("[SystemCall] SDKLIB_IME_ActiveCtrl\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_IsActiveInputer (void) {printf("[SystemCall] SDKLIB_IME_IsActiveInputer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_SetDefault (void) {printf("[SystemCall] SDKLIB_IME_SetDefault\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_GetLXResult (void) {printf("[SystemCall] SDKLIB_IME_GetLXResult\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_SetHandFilter (void) {printf("[SystemCall] SDKLIB_IME_SetHandFilter\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_GetHandFilter (void) {printf("[SystemCall] SDKLIB_IME_GetHandFilter\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_IsFuncKey (void) {printf("[SystemCall] SDKLIB_IME_IsFuncKey\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_SearchKeyMap (void) {printf("[SystemCall] SDKLIB_IME_SearchKeyMap\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_IsSelectKey (void) {printf("[SystemCall] SDKLIB_IME_IsSelectKey\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_SaveUserInfo (void) {printf("[SystemCall] SDKLIB_IME_SaveUserInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_ReadUserInfo (void) {printf("[SystemCall] SDKLIB_IME_ReadUserInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_IsEmptyFont (void) {printf("[SystemCall] SDKLIB_IME_IsEmptyFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_SetHandWrtConfig (void) {printf("[SystemCall] SDKLIB_IME_SetHandWrtConfig\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_SetHandWrtStudyFlag (void) {printf("[SystemCall] SDKLIB_IME_SetHandWrtStudyFlag\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_SetRecognizeFlag (void) {printf("[SystemCall] SDKLIB_IME_SetRecognizeFlag\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_GetCtrl (void) {printf("[SystemCall] SDKLIB_IME_GetCtrl\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_GetCtrlState (void) {printf("[SystemCall] SDKLIB_IME_GetCtrlState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_GetViewInfo (void) {printf("[SystemCall] SDKLIB_IME_GetViewInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SCcorrection (void) {printf("[SystemCall] SDKLIB_SCcorrection\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SCwildcard (void) {printf("[SystemCall] SDKLIB_SCwildcard\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SCverify (void) {printf("[SystemCall] SDKLIB_SCverify\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InitialSpelling (void) {printf("[SystemCall] SDKLIB_InitialSpelling\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SCopenDatabase (void) {printf("[SystemCall] SDKLIB_SCopenDatabase\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SCcloseDatabase (void) {printf("[SystemCall] SDKLIB_SCcloseDatabase\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SCGetMaxWordLen (void) {printf("[SystemCall] SDKLIB_SCGetMaxWordLen\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetTotalItem (void) {printf("[SystemCall] SDKLIB_GetTotalItem\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMaxBlockSize (void) {printf("[SystemCall] SDKLIB_GetMaxBlockSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetKeyWord (void) {printf("[SystemCall] SDKLIB_GetKeyWord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetAllContent (void) {printf("[SystemCall] SDKLIB_GetAllContent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetSaveAddress (void) {printf("[SystemCall] SDKLIB_GetSaveAddress\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetAlpExit (void) {printf("[SystemCall] SDKLIB_GetAlpExit\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetAlpExit (void) {printf("[SystemCall] SDKLIB_SetAlpExit\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetDictFont (void) {printf("[SystemCall] SDKLIB_SetDictFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetDictFont (void) {printf("[SystemCall] SDKLIB_GetDictFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UniversalCrossSearch (void) {printf("[SystemCall] SDKLIB_UniversalCrossSearch\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UniversalDictList (void) {printf("[SystemCall] SDKLIB_UniversalDictList\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UniversalDictListForAll (void) {printf("[SystemCall] SDKLIB_UniversalDictListForAll\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UniversalCardList (void) {printf("[SystemCall] SDKLIB_UniversalCardList\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SearchEveryWay (void) {printf("[SystemCall] SDKLIB_SearchEveryWay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetAddDictPosInList (void) {printf("[SystemCall] SDKLIB_GetAddDictPosInList\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCurrentCardDictNum (void) {printf("[SystemCall] SDKLIB_GetCurrentCardDictNum\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SearchCurrentCardDictInfo (void) {printf("[SystemCall] SDKLIB_SearchCurrentCardDictInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ReleaseCardDictInfo (void) {printf("[SystemCall] SDKLIB_ReleaseCardDictInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_SetBufferAttrib (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_SetBufferAttrib\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_SpeechForRich (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_SpeechForRich\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IsDictOuYu (void) {printf("[SystemCall] SDKLIB_IsDictOuYu\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateRichView (void) {printf("[SystemCall] SDKLIB_CreateRichView\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_AddScrollBarToRichview (void) {printf("[SystemCall] SDKLIB_AddScrollBarToRichview\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeScrollBarToRichview (void) {printf("[SystemCall] SDKLIB_ChangeScrollBarToRichview\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ChangeScrollBarPos (void) {printf("[SystemCall] SDKLIB_ChangeScrollBarPos\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetDisplayMode (void) {printf("[SystemCall] SDKLIB_SetDisplayMode\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetShowSearchLayer (void) {printf("[SystemCall] SDKLIB_SetShowSearchLayer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetWindowState (void) {printf("[SystemCall] SDKLIB_SetWindowState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetWindowState (void) {printf("[SystemCall] SDKLIB_GetWindowState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetBaseLine (void) {printf("[SystemCall] SDKLIB_GetBaseLine\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetBaseLine (void) {printf("[SystemCall] SDKLIB_SetBaseLine\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_BackupWindowState (void) {printf("[SystemCall] SDKLIB_BackupWindowState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RestoreWindowState (void) {printf("[SystemCall] SDKLIB_RestoreWindowState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_draw (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_handleEvent (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMarkString (void) {printf("[SystemCall] SDKLIB_GetMarkString\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetRichWindowState (void) {printf("[SystemCall] SDKLIB_GetRichWindowState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetShowMode (void) {printf("[SystemCall] SDKLIB_SetShowMode\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_ShowSearchLayer (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_ShowSearchLayer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_SetStateForUser (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_SetStateForUser\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_WriteString (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_WriteString\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RichViewSetColor (void) {printf("[SystemCall] SDKLIB_RichViewSetColor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetTotalLine (void) {printf("[SystemCall] SDKLIB_SetTotalLine\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ShowRichContentOnly (void) {printf("[SystemCall] SDKLIB_ShowRichContentOnly\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_SetCttsType (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_SetCttsType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetDefLineEditorInfo (void) {printf("[SystemCall] SDKLIB_SetDefLineEditorInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LineEditor (void) {printf("[SystemCall] SDKLIB_LineEditor\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LineEditor_handleEvent (void) {printf("[SystemCall] SDKLIB_LineEditor_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DictEditor_handleEvent (void) {printf("[SystemCall] SDKLIB_DictEditor_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LEModuleForUser (void) {printf("[SystemCall] SDKLIB_LEModuleForUser\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LineEditor_ModuleForUser (void) {printf("[SystemCall] SDKLIB_LineEditor_ModuleForUser\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LEDictWiseSearch (void) {printf("[SystemCall] SDKLIB_LEDictWiseSearch\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IsWildCard (void) {printf("[SystemCall] SDKLIB_IsWildCard\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LEditor_draw (void) {printf("[SystemCall] SDKLIB_LEditor_draw\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LINEEDITOR_changeFocuseAct (void) {printf("[SystemCall] SDKLIB_LINEEDITOR_changeFocuseAct\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LEDSK_handleEvent (void) {printf("[SystemCall] SDKLIB_LEDSK_handleEvent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LineEditorCompareStr (void) {printf("[SystemCall] SDKLIB_LineEditorCompareStr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LineEditorWiseSearch (void) {printf("[SystemCall] SDKLIB_LineEditorWiseSearch\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SearchDict (void) {printf("[SystemCall] SDKLIB_SearchDict\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetSearchDictShortName (void) {printf("[SystemCall] SDKLIB_GetSearchDictShortName\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCurrentMainDictNum (void) {printf("[SystemCall] SDKLIB_GetCurrentMainDictNum\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_OKSpeechForRich (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_OKSpeechForRich\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetIndexHcaOffset (void) {printf("[SystemCall] SDKLIB_GetIndexHcaOffset\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetIndexIconOffset (void) {printf("[SystemCall] SDKLIB_GetIndexIconOffset\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetAppIndexIconOffset (void) {printf("[SystemCall] SDKLIB_GetAppIndexIconOffset\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadHCAToGraphicByIdx (void) {printf("[SystemCall] SDKLIB_LoadHCAToGraphicByIdx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadHCAToGraphicHeadByIdx (void) {printf("[SystemCall] SDKLIB_LoadHCAToGraphicHeadByIdx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetIndexHCAHeight (void) {printf("[SystemCall] SDKLIB_GetIndexHCAHeight\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetIndexHCAWidth (void) {printf("[SystemCall] SDKLIB_GetIndexHCAWidth\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ShowHCAByOffset (void) {printf("[SystemCall] SDKLIB_ShowHCAByOffset\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetHCATransparentMode (void) {printf("[SystemCall] SDKLIB_SetHCATransparentMode\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ReleaseHcaCache (void) {printf("[SystemCall] SDKLIB_ReleaseHcaCache\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ResetCache (void) {printf("[SystemCall] SDKLIB_ResetCache\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetLibDataindexOffset (void) {printf("[SystemCall] SDKLIB_SetLibDataindexOffset\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetLibAddrFromID (void) {printf("[SystemCall] SDKLIB_GetLibAddrFromID\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ShowBookProFromFile (void) {printf("[SystemCall] SDKLIB_ShowBookProFromFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RunBook (void) {printf("[SystemCall] SDKLIB_RunBook\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ShowBook (void) {printf("[SystemCall] SDKLIB_ShowBook\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ShowBookPreview (void) {printf("[SystemCall] SDKLIB_ShowBookPreview\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ShowBookEx (void) {printf("[SystemCall] SDKLIB_ShowBookEx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_USBMassStorageRun (void) {printf("[SystemCall] SDKLIB_USBMassStorageRun\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetPassThroughCallBack (void) {printf("[SystemCall] SDKLIB_SetPassThroughCallBack\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ctts_predict (void) {printf("[SystemCall] SDKLIB_ctts_predict\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ctts_nounce (void) {printf("[SystemCall] SDKLIB_ctts_nounce\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetAllVoiceState (void) {printf("[SystemCall] SDKLIB_SetAllVoiceState\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_OpenPCMCodec (void) {printf("[SystemCall] SDKLIB_OpenPCMCodec\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ClosePCMCodec (void) {printf("[SystemCall] SDKLIB_ClosePCMCodec\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_AudioPlayBackPause (void) {printf("[SystemCall] SDKLIB_AudioPlayBackPause\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_AudioPlayBackContinue (void) {printf("[SystemCall] SDKLIB_AudioPlayBackContinue\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PlayWaveData (void) {printf("[SystemCall] SDKLIB_PlayWaveData\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_StopWaveDataPlay (void) {printf("[SystemCall] SDKLIB_StopWaveDataPlay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PauseWaveDataPlay (void) {printf("[SystemCall] SDKLIB_PauseWaveDataPlay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ContinueWaveDataPlay (void) {printf("[SystemCall] SDKLIB_ContinueWaveDataPlay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RecordAdpcmEx (void) {printf("[SystemCall] SDKLIB_RecordAdpcmEx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_StopADPCMRecord (void) {printf("[SystemCall] SDKLIB_StopADPCMRecord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IsWaveDataPlayStopped (void) {printf("[SystemCall] SDKLIB_IsWaveDataPlayStopped\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PlayMP3Data (void) {printf("[SystemCall] SDKLIB_PlayMP3Data\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_StopMP3DataPlay (void) {printf("[SystemCall] SDKLIB_StopMP3DataPlay\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PausePlayMP3Data (void) {printf("[SystemCall] SDKLIB_PausePlayMP3Data\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ContinuePlayMP3Data (void) {printf("[SystemCall] SDKLIB_ContinuePlayMP3Data\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InitBestlkHandle (void) {printf("[SystemCall] SDKLIB_InitBestlkHandle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetBestlkVoiceHandle (void) {printf("[SystemCall] SDKLIB_SetBestlkVoiceHandle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_RegistInputer (void) {printf("[SystemCall] SDKLIB_IME_RegistInputer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetLanguageAttr (void) {printf("[SystemCall] SDKLIB_SetLanguageAttr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetDialectAttr (void) {printf("[SystemCall] SDKLIB_SetDialectAttr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetLineEditorAttr (void) {printf("[SystemCall] SDKLIB_SetLineEditorAttr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetBookLibDataHFile (void) {printf("[SystemCall] SDKLIB_SetBookLibDataHFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetBookVocLibDataHFile (void) {printf("[SystemCall] SDKLIB_SetBookVocLibDataHFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_SetGlobalVar (void) {printf("[SystemCall] SDKLIB_IME_SetGlobalVar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_IME_Functions (void) {printf("[SystemCall] SDKLIB_IME_Functions\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LE_SupportMultiLangFunc (void) {printf("[SystemCall] SDKLIB_LE_SupportMultiLangFunc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ShowBookFromHANDLE (void) {printf("[SystemCall] SDKLIB_ShowBookFromHANDLE\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfnsplit (void) {printf("[SystemCall] SDKLIB__wfnsplit\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfnmerge (void) {printf("[SystemCall] SDKLIB__wfnmerge\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfcreate (void) {printf("[SystemCall] SDKLIB__wfcreate\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfcreateSz (void) {printf("[SystemCall] SDKLIB__wfcreateSz\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___wfopen (void) {printf("[SystemCall] SDKLIB___wfopen\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfindfirst (void) {printf("[SystemCall] SDKLIB__wfindfirst\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfindnext (void) {printf("[SystemCall] SDKLIB__wfindnext\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfgetattr (void) {printf("[SystemCall] SDKLIB__wfgetattr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfsetattr (void) {printf("[SystemCall] SDKLIB__wfsetattr\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___wremove (void) {printf("[SystemCall] SDKLIB___wremove\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wrename (void) {printf("[SystemCall] SDKLIB__wrename\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfcopy (void) {printf("[SystemCall] SDKLIB__wfcopy\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wmkdir (void) {printf("[SystemCall] SDKLIB__wmkdir\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wrmdir (void) {printf("[SystemCall] SDKLIB__wrmdir\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wchdir (void) {printf("[SystemCall] SDKLIB__wchdir\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wgetcurdir (void) {printf("[SystemCall] SDKLIB__wgetcurdir\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afsettime (void) {printf("[SystemCall] SDKLIB__afsettime\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfsettime (void) {printf("[SystemCall] SDKLIB__wfsettime\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__afullpath (void) {printf("[SystemCall] SDKLIB__afullpath\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__wfullpath (void) {printf("[SystemCall] SDKLIB__wfullpath\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RunApplicationW (void) {printf("[SystemCall] SDKLIB_RunApplicationW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetApplicationNameW (void) {printf("[SystemCall] SDKLIB_GetApplicationNameW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadProgramW (void) {printf("[SystemCall] SDKLIB_LoadProgramW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCurrentPathW (void) {printf("[SystemCall] SDKLIB_GetCurrentPathW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ProgramIsRunningW (void) {printf("[SystemCall] SDKLIB_ProgramIsRunningW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadHFileProgramW (void) {printf("[SystemCall] SDKLIB_LoadHFileProgramW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadHFileProgramA (void) {printf("[SystemCall] SDKLIB_LoadHFileProgramA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__LoadLibraryA (void) {printf("[SystemCall] SDKLIB__LoadLibraryA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetModuleFileNameA (void) {printf("[SystemCall] SDKLIB__GetModuleFileNameA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetModuleHandleA (void) {printf("[SystemCall] SDKLIB__GetModuleHandleA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetApplicationProcA (void) {printf("[SystemCall] SDKLIB_GetApplicationProcA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_StayResidentProgramA (void) {printf("[SystemCall] SDKLIB_StayResidentProgramA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UnStayResidentProgramA (void) {printf("[SystemCall] SDKLIB_UnStayResidentProgramA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CheckProgramIsStayResident (void) {printf("[SystemCall] SDKLIB_CheckProgramIsStayResident\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__FindResourceA (void) {printf("[SystemCall] SDKLIB__FindResourceA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__FindResourceExA (void) {printf("[SystemCall] SDKLIB__FindResourceExA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__LoadLibraryW (void) {printf("[SystemCall] SDKLIB__LoadLibraryW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetModuleFileNameW (void) {printf("[SystemCall] SDKLIB__GetModuleFileNameW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetModuleHandleW (void) {printf("[SystemCall] SDKLIB__GetModuleHandleW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetApplicationProcW (void) {printf("[SystemCall] SDKLIB_GetApplicationProcW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__FindResourceW (void) {printf("[SystemCall] SDKLIB__FindResourceW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__FindResourceExW (void) {printf("[SystemCall] SDKLIB__FindResourceExW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_StayResidentProgramW (void) {printf("[SystemCall] SDKLIB_StayResidentProgramW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UnStayResidentProgramW (void) {printf("[SystemCall] SDKLIB_UnStayResidentProgramW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__FreeLibrary (void) {printf("[SystemCall] SDKLIB__FreeLibrary\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetProcAddress (void) {printf("[SystemCall] SDKLIB__GetProcAddress\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__SizeofResource (void) {printf("[SystemCall] SDKLIB__SizeofResource\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__OpenResourceItemFile (void) {printf("[SystemCall] SDKLIB__OpenResourceItemFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__CloseResourceItemFile (void) {printf("[SystemCall] SDKLIB__CloseResourceItemFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCardSN (void) {printf("[SystemCall] SDKLIB_GetCardSN\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetCardSize (void) {printf("[SystemCall] SDKLIB_GetCardSize\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetThaiWord (void) {printf("[SystemCall] SDKLIB_GetThaiWord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadThaiGrammarLib (void) {printf("[SystemCall] SDKLIB_LoadThaiGrammarLib\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FreeThaiGrammarLib (void) {printf("[SystemCall] SDKLIB_FreeThaiGrammarLib\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WriteComDebugMsg (void) {printf("[SystemCall] SDKLIB_WriteComDebugMsg\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateIconButton (void) {printf("[SystemCall] SDKLIB_CreateIconButton\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadImageFile (void) {printf("[SystemCall] SDKLIB_LoadImageFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetResourceCfg (void) {printf("[SystemCall] SDKLIB_GetResourceCfg\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetSystemDefaultLangID (void) {printf("[SystemCall] SDKLIB_GetSystemDefaultLangID\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetSystemDefaultLangID (void) {printf("[SystemCall] SDKLIB_SetSystemDefaultLangID\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateFile (void) {printf("[SystemCall] SDKLIB_CreateFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DeleteFile (void) {printf("[SystemCall] SDKLIB_DeleteFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_ReadFile (void) {printf("[SystemCall] SDKLIB_ReadFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_WriteFile (void) {printf("[SystemCall] SDKLIB_WriteFile\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetFilePointer (void) {printf("[SystemCall] SDKLIB_SetFilePointer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DeviceIoControl (void) {printf("[SystemCall] SDKLIB_DeviceIoControl\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CloseHandle (void) {printf("[SystemCall] SDKLIB_CloseHandle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DictLastWord (void) {printf("[SystemCall] SDKLIB_DictLastWord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetTransBuffer (void) {printf("[SystemCall] SDKLIB_GetTransBuffer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DictIsYuanYinPhonetic (void) {printf("[SystemCall] SDKLIB_DictIsYuanYinPhonetic\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_InsertButtonTeam (void) {printf("[SystemCall] SDKLIB_InsertButtonTeam\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_CreateSearchInfo (void) {printf("[SystemCall] SDKLIB_CreateSearchInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FreeSearchInfo (void) {printf("[SystemCall] SDKLIB_FreeSearchInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DefProcessContent (void) {printf("[SystemCall] SDKLIB_DefProcessContent\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DefInsertPic (void) {printf("[SystemCall] SDKLIB_DefInsertPic\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DefGetWholeWord (void) {printf("[SystemCall] SDKLIB_DefGetWholeWord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_DefAddALine (void) {printf("[SystemCall] SDKLIB_DefAddALine\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_GetFlagLength (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_GetFlagLength\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_FilterMark (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_FilterMark\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_AddNewWord (void) {printf("[SystemCall] SDKLIB_AddNewWord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMaxSearchLayer (void) {printf("[SystemCall] SDKLIB_GetMaxSearchLayer\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FormatMessage (void) {printf("[SystemCall] SDKLIB_FormatMessage\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetFont (void) {printf("[SystemCall] SDKLIB_SetFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetFont (void) {printf("[SystemCall] SDKLIB_GetFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetFontWidth (void) {printf("[SystemCall] SDKLIB_GetFontWidth\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetStringLengthEx (void) {printf("[SystemCall] SDKLIB_GetStringLengthEx\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetFontStyle (void) {printf("[SystemCall] SDKLIB_SetFontStyle\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_RegisterUserFont (void) {printf("[SystemCall] SDKLIB_RegisterUserFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_UnRegisterUserFont (void) {printf("[SystemCall] SDKLIB_UnRegisterUserFont\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetCurrentVideoDevice (void) {printf("[SystemCall] SDKLIB_SetCurrentVideoDevice\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_SetSupportDoubleLCD (void) {printf("[SystemCall] SDKLIB_SetSupportDoubleLCD\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__GetDriverType (void) {printf("[SystemCall] SDKLIB__GetDriverType\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_EditControlFunc (void) {printf("[SystemCall] SDKLIB_EditControlFunc\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMasterSerialNumber (void) {printf("[SystemCall] SDKLIB_GetMasterSerialNumber\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetMasterVendorInfo (void) {printf("[SystemCall] SDKLIB_GetMasterVendorInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_PRICHVIEW_SetDisplayPosition (void) {printf("[SystemCall] SDKLIB_PRICHVIEW_SetDisplayPosition\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetApplicationHeadInfoA (void) {printf("[SystemCall] SDKLIB_GetApplicationHeadInfoA\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetApplicationHeadInfoW (void) {printf("[SystemCall] SDKLIB_GetApplicationHeadInfoW\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__FreeFindResInfo (void) {printf("[SystemCall] SDKLIB__FreeFindResInfo\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_GetWholeWord (void) {printf("[SystemCall] SDKLIB_GetWholeWord\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_LoadWordGrammarLib (void) {printf("[SystemCall] SDKLIB_LoadWordGrammarLib\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_FreeWordGrammarLib (void) {printf("[SystemCall] SDKLIB_FreeWordGrammarLib\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_mount_file_disk (void) {printf("[SystemCall] SDKLIB_mount_file_disk\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB_umount_file_disk (void) {printf("[SystemCall] SDKLIB_umount_file_disk\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___close (void) {printf("[SystemCall] SDKLIB___close\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___commit (void) {printf("[SystemCall] SDKLIB___commit\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___creat (void) {printf("[SystemCall] SDKLIB___creat\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___dup (void) {printf("[SystemCall] SDKLIB___dup\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___wcreat (void) {printf("[SystemCall] SDKLIB___wcreat\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___eof (void) {printf("[SystemCall] SDKLIB___eof\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___get_errno (void) {printf("[SystemCall] SDKLIB___get_errno\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___lseek (void) {printf("[SystemCall] SDKLIB___lseek\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___lseeki64 (void) {printf("[SystemCall] SDKLIB___lseeki64\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___open (void) {printf("[SystemCall] SDKLIB___open\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___wopen (void) {printf("[SystemCall] SDKLIB___wopen\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___read (void) {printf("[SystemCall] SDKLIB___read\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___set_errno (void) {printf("[SystemCall] SDKLIB___set_errno\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___tell (void) {printf("[SystemCall] SDKLIB___tell\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___telli64 (void) {printf("[SystemCall] SDKLIB___telli64\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___truncate (void) {printf("[SystemCall] SDKLIB___truncate\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB___write (void) {printf("[SystemCall] SDKLIB___write\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__MultiByteToWideChar (void) {printf("[SystemCall] SDKLIB__MultiByteToWideChar\n");return 0;}
__attribute__((weak)) uint32_t SDKLIB__WideCharToMultiByte (void) {printf("[SystemCall] SDKLIB__WideCharToMultiByte\n");return 0;}
